## Biker Store Database

#### You’re working for a bike company and they want to:

#### Increase revenue
#### Understand customers
#### Optimize inventory
#### Improve operations

In [230]:
import pandas as pd
import sqlite3

In [231]:
brands_df=pd.read_csv('brands.csv')
categories_df=pd.read_csv('categories.csv')
customers_df=pd.read_csv('customers (1).csv')
order_items_df=pd.read_csv('order_items.csv')
orders_df=pd.read_csv('orders.csv')
products_df=pd.read_csv('products.csv')
staffs_df=pd.read_csv('staffs.csv')
stocks_df=pd.read_csv('stocks.csv')
stores_df=pd.read_csv('stores.csv')

In [232]:
brands_df.head(5)

   brand_id   brand_name
0         1      Electra
1         2         Haro
2         3       Heller
3         4  Pure Cycles
4         5      Ritchey

In [233]:
categories_df.head()

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes

In [234]:
customers_df.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [235]:
order_items_df.head()

   order_id  item_id  product_id  quantity  list_price  discount
0         1        1          20         1      599.99      0.20
1         1        2           8         2     1799.99      0.07
2         1        3          10         2     1549.00      0.05
3         1        4          16         2      599.99      0.05
4         1        5           4         1     2899.99      0.20

In [236]:
orders_df.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [237]:
products_df.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [238]:
staffs_df.head()

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [239]:
stocks_df.head()

   store_id  product_id  quantity
0         1           1        27
1         1           2         5
2         1           3         6
3         1           4        23
4         1           5        22

In [240]:
stores_df.head()

,store_id,store_name,phone,email,street,city,state,zip_code
0,1,Santa Cruz Bikes,(831) 476-4321,santacruz@bikes.shop,3700 Portola Drive,Santa Cruz,CA,95060
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088

In [241]:
conn=sqlite3.connect('bike_store.db')

In [242]:
brands_df.to_sql("brands",conn,if_exists='replace',index=False)
categories_df.to_sql("categories",conn,if_exists='replace',index=False)
customers_df.to_sql("customers",conn,if_exists='replace',index=False)
order_items_df.to_sql("order_items",conn,if_exists='replace',index=False)
orders_df.to_sql("orders",conn,if_exists='replace',index=False)
products_df.to_sql("products",conn,if_exists='replace',index=False)
staffs_df.to_sql("staff",conn,if_exists='replace',index=False)
stocks_df.to_sql("stocks",conn,if_exists='replace',index=False)
stores_df.to_sql("stores",conn,if_exists='replace',index=False)

3

In [243]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';",conn)

          name
0       brands
1   categories
2    customers
3  order_items
4       orders
5     products
6        staff
7       stocks
8       stores

## Data Analysis

### 1. Bikes with the most revenue

In [244]:
pd.read_sql("SELECT p.product_name, SUM(oi.quantity * oi.list_price) AS revenue FROM order_items oi JOIN products p ON oi.product_id=p.product_id GROUP BY product_name ORDER BY revenue DESC LIMIT 5;",conn)

                    product_name    revenue
0       Trek Slash 8 27.5 - 2016  615998.46
1           Trek Conduit+ - 2016  434998.55
2       Trek Fuel EX 8 29 - 2016  414698.57
3    Surly Straggler 650b - 2016  253829.49
4  Trek Domane SLR 6 Disc - 2017  236499.57

#### Trek Slash 8 27.5-2016 earns the Biker store the most revenue and the company might invest in these bikes to earn more revenue.

### 2. Most expensive bikes

In [245]:
pd.read_sql("SELECT product_name,list_price FROM products ORDER BY list_price DESC LIMIT 5;",conn)

                             product_name  list_price
0           Trek Domane SLR 9 Disc - 2018    11999.99
1           Trek Domane SLR 8 Disc - 2018     7499.99
2        Trek Silque SLR 8 Women's - 2017     6499.99
3          Trek Domane SL Frameset - 2018     6499.99
4  Trek Domane SL Frameset Women's - 2018     6499.99

#### The Trek Domane and silque brand bikes are the most expensive bikes in the store

### 3. Orders made per customer

In [253]:
pd.read_sql("SELECT customer_id,COUNT(order_id) as total_orders FROM orders GROUP BY customer_id ORDER BY total_orders DESC LIMIT 10;",conn)

   customer_id  total_orders
0          116             3
1           77             3
2           68             3
3           66             3
4           64             3
5           61             3
6           56             3
7           53             3
8           50             3
9           47             3

### 4. Most valuable customer

In [247]:
pd.read_sql("SELECT c.first_name,c.last_name, SUM(quantity * list_price) AS total_amount_spent FROM customers c JOIN orders o ON c.customer_id=o.customer_id JOIN order_items oi ON o.order_id=oi.order_id GROUP BY c.first_name,c.last_name ORDER BY total_amount_spent DESC LIMIT 1;",conn)

  first_name last_name  total_amount_spent
0    Pamelia    Newman            37801.84

#### Pamelia Newman is store's most valuable customer with highest amount spent on bikes

### 5. Bike Categories with most sales

In [248]:
pd.read_sql("SELECT c.category_name, SUM(oi.quantity * oi.list_price) AS sales FROM categories c JOIN products p ON c.category_id=p.category_id JOIN order_items oi ON p.product_id=oi.product_id GROUP BY category_name ORDER BY sales DESC LIMIT 5;",conn)

         category_name       sales
0       Mountain Bikes  3030775.71
1           Road Bikes  1852555.60
2    Cruisers Bicycles  1109151.04
3       Electric Bikes  1020236.85
4  Cyclocross Bicycles   799874.60

In [249]:
pd.read_sql("SELECT c.category_name, SUM(oi.quantity * oi.list_price) AS sales FROM categories c JOIN products p ON c.category_id=p.category_id JOIN order_items oi ON p.product_id=oi.product_id GROUP BY category_name ORDER BY sales ASC LIMIT 2;",conn)

       category_name      sales
0  Children Bicycles  327888.21
1   Comfort Bicycles  438506.87

#### Mountain bikes have the most sales in the biker store followed by road bikes while children bicycles and comfort bicycles hae the lowest sales in the Biker Store therefore the Biker store could invest in more mountain bikes for more sales

#### 6. Stock levels in the Store

In [250]:
pd.read_sql("SELECT store_name,SUM(st.quantity) AS stock_levels FROM stores s JOIN stocks st ON s.store_id=st.store_id GROUP BY store_name ORDER BY stock_levels ASC;",conn)

         store_name  stock_levels
0     Baldwin Bikes          4359
1  Santa Cruz Bikes          4532
2     Rowlett Bikes          4620

In [251]:
pd.read_sql("SELECT product_name,SUM(st.quantity) AS stock_levels FROM products p JOIN stocks st ON p.product_id=st.product_id GROUP BY product_name ORDER BY stock_levels ASC LIMIT 5;",conn)

                                product_name  stock_levels
0            Trek Domane SLR Frameset - 2018             5
1             Electra Superbolt 1 20" - 2018             9
2           Electra Cruiser 1 Ladies' - 2018            10
3  Electra Amsterdam Original 3i - 2015/2017            11
4            Sun Bicycles Streamway 7 - 2017            11

#### The Baldwin Bikes store has the lowest stock of bikes among other stores while Trek Domane SLR Frameset - 2018 is the lowest stocked  bicycle and the Biker store needs add more bikes.